### ISSUE TITLE
Support detection for Tiltfile

### ISSUE THREAD

**Issue by abatilo** [cappyzawa/starlark.vim#2]
https://tilt.dev/

Tilt has been gaining popularity and it would be great to have this plugin also detect `Tiltfile.*` as a starlark file.

**Comment by cappyzawa** [comment]
@abatilo Thanks for your report 👍 

I added this change.
The following files are detected as starlark file.
* `Tiltfile`
* `Tilefile.foo`
* `Tilefilefoo`

**Comment by diefans** [comment]
I think the fix is wrong, IMHO it should not change the filetype, but just apply the syntax. Since there is a LSP for Tiltfile, changing the filetype prevents LSP loading...

```
    autocmd BufNewFile,BufRead Tiltfile* setlocal ft=tiltfile syntax=starlark
```

Further I think this setting does not belong into this repo, but into the users config...

**Comment by cappyzawa** [comment]
@diefans Thanks for your comment.

I agree with you.
I'll revert https://github.com/cappyzawa/starlark.vim/commit/fd6060fade298aad22a1767680c3a10d2aca2fad

**Comment by cappyzawa** [comment]
I've reverted it.
